image: jakzal/phpqa:php8.2

before_script:
    - composer install

cache:
      paths:
        - vendor/

stages:
      - CodingStandards
      - UnitTests

phpcs:
      stage: CodingStandards
      script: phpcs -v --standard=PSR12 --ignore=./src/Kernel/php ./src 
      allow_failure: false

phpstan:
      stage: CodingStandards
      script: phpstan analyse ./src 
      allow_failure: false

twig-lint:
      stage: CodingStandards
      script: twig-lint lint ./templates
      allow_failure: false

phpunit:
      stage: UnitTests
      script:
        - php bin/phpunit
      allow_failure: false
