version: "3.8"

services:
  ###> doctrine/doctrine-bundle ###
  db:
    image: mysql
    container_name: Exsana
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_exsana
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks: 
      - dev

  www:
    build: docker
    container_name: www_exsana
    ports:
      - "8000:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev
    # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
    # - ./docker/db/data:/var/lib/postgresql/data:rw
    ###< doctrine/doctrine-bundle ###

volumes:
  ###< symfony/mercure-bundle ###
  ###> doctrine/doctrine-bundle ###
  db-data: ###< doctrine/doctrine-bundle ###

networks:
  dev:
