parameters:
    pedago_directory: '%kernel.project_dir%/public/uploads/pedago'
    email.from_address: 'exsanaformation@gmail.com'
    email.from_name: 'Notification Exsana Formation'
    email.admin_address: 'exsanaformation@gmail.com'

services:
    App\Service\UserRegistrationService:
        class: App\Service\UserRegistrationService
        arguments:
            $mailer: '@Symfony\Component\Mailer\MailerInterface'

    App\Service\ErrorLogger:
        arguments:
            $logger: '@logger'


    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude:
            - '../src/{DependencyInjection,Entity,Kernel.php}'
