parameters:
    pedago_directory: '%kernel.project_dir%/public/uploads/pedago'

services:
    _defaults:
        autowire: true
        autoconfigure: true 

    App\:
        resource: '../src/*'
        exclude:
            - '../src/{DependencyInjection,Entity,Kernel.php}'